### PR TITLE
Support IE11 download using onClick handler

### PR DESCRIPTION
**Pull request by hindmanj**

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Tested this - works as expected.

@abdennour any hope we can get this merged in? I'd hate to have to fork and publish a separate repo with updates

**Comment by abdennour** [comment]
Please fix failed unit-tests before?

**Comment by hindmanj** [comment]
This does not break the unit tests.  Coverage decreased due to the IE11 code workaround, which can only be tested in IE11, since it is a browser specific anomaly.  Manual testing has been performed, both by us and the community as indicated in this PR, and we use this in our production customer portal which requires IE11 support.

Our options are either to maintain our own fork, which is silly for the amount of code changed or stop using this component, because we cannot lock ourselves to an old and unsupported version of our components.

Because this has been open for so long, we are accumulating merge conflicts from the CDN versions.  According to your own documentation, coverage must be above 80%, which is true for this PR.

**Comment by abdennour** [comment]
Thank you @hindmanj  for the swift response . If you could resolve conflict I will be more than happy. Also I will add you as collaborator in github , but I need also your NPM username to add you there.

**Comment by abdennour** [comment]
@hindmanj  also "lib" directory needs to be ignored . However , it will be considered in the NPM.

**Comment by abdennour** [comment]
Once you are done. Please notify me [here](http://in.abdennoor.com)

**Pull request closed without merging**
