### PR TITLE
Support download feature for Safari on mac (not open a new tab)

### PR DESCRIPTION
**Pull request by leejaen**

### CODE REVIEW

**Comment by sjandro** [comment]
What was the issue with the PR? I am really hoping this makes it to master.

**Comment by leejaen** [comment]
[https://github.com/abdennour/react-csv/issues/24](https://github.com/abdennour/react-csv/issues/24)

**Comment by coldfish** [comment]
@leejaen Compiled the fix, but I don't understand why the file is downloaded as a "Unknown" name. Something is missing..

**Comment by mccabemj** [comment]
This was changed and implemented in #108

**Pull request closed without merging**
