### PR TITLE
Fix safari download

### PR DESCRIPTION
**Pull request by gion**
I know this has been issued before (#24), but the problem still exists.
Inspired from #48 (btw, thanks @leejaen 👍), I want to submit this PR to solve the safari related issues I'm having.

### CODE REVIEW

**Comment by gion** [comment]
@mccabemj , sorry for that [insert embarrased emoji here].
I pushed another commit that removes the `debugger`.
Thanks!

**Comment by gion** [comment]
Thanks! 👍 
@mccabemj @abdennour Do you happen to know when this patch is going to be released on npm?

**Comment by mccabemj** [comment]
@gion just published it now. Thanks for your contribution!

**Comment by gion** [comment]
Wow, that was fast. 
Thanks!
Keep up the good work ;)

**Comment by leejaen** [comment]
GREAT JOB!!!!

**Pull request merged**
