### PR TITLE
added prop flag to suppress \uFEFF

### PR DESCRIPTION
**Pull request by jimulle**
resolves issue with \uFEFF in csv URI identified in [issue #22](https://github.com/abdennour/react-csv/issues/22)

### CODE REVIEW

**Comment by timt** [comment]
Please can you merge this as we need this also

**Comment by thehammer** [comment]
+1. Please publish a new package as well.

**Comment by abdennour** [comment]
Oh! My community.I am really sorry. I will do it right now. Please elect someone to take over// Who is ready?

**Comment by jimulle** [comment]
@abdennour I may be interested if you are looking to offload the repository

**Pull request merged**
