### PR TITLE
Allow custom header labels to be used for data that is of type object

### PR DESCRIPTION
**Pull request by fcwheat**
When working with data that was an array of objects, I found myself wanting to have the headers be named differently than the keys that were within the objects. For example, if my data had a field named `firstName` I didn't want `firstName` to show up as the header on the CSV, but rather, `First Name`. These changes implement this feature.

### CODE REVIEW

**Comment by bmuenzenmeyer** [comment]
Tested this - works as expected.

@abdennour any hope we can get this merged in? I'd hate to have to fork and publish a separate repo with updates

**Comment by jimulle** [comment]
Why is `node-sass` a dependency now? Where/how is it being used?

**Comment by fcwheat** [comment]
@jimulle `node-sass` was added in due to seeing the following when I first installed the dependencies:
`"sass-loader@4.1.1" has unmet peer dependency "node-sass@^3.4.2 || ^4.0.0".` `sass-loader` was an existing dev dependency.

Both `documentation` and `node-sass` should be listed within devDependencies and having them within dependencies was incorrect.

**Comment by jimulle** [comment]
are we actually using the sass-loader for something or are the superfluous, unnecessary dependencies?

**Comment by fcwheat** [comment]
I certainly wasn't using it for anything and a quick check for `.scss` files doesn't yield anything so I am thinking unnecessary. 

@abdennour would know for sure however, as the sass-loader within the webpack config looks to first have been added in this commit: 298ca64

**Pull request merged**
