### PR TITLE
fix server side rendering

### LINKED ISSUE #87: Breaks with server-side rendering
I'm using [Nextjs](https://nextjs.org/) which is server-side rendering the app. When I use the library I get:

> { ReferenceError: Blob is not defined
>     at buildURI (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-csv/lib/core.js:87:14)
>     at CSVLink.buildURI (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-csv/lib/components/Link.js:44:29)
>     at CSVLink.render (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-csv/lib/components/Link.js:78:22)
>     at processChild (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2204:18)
>     at resolve (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2061:5)
>     at ReactDOMServerRenderer.render (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2380:22)
>     at ReactDOMServerRenderer.read (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2354:19)
>     at renderToString (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/react-dom/cjs/react-dom-server.node.development.js:2726:25)
>     at renderPage (/Users/praca/Desktop/Projekty/move-dashboard/node_modules/next/dist/server/render.js:275:26)
>     at Function.getInitialProps (pages/_document.jsx:14:0)

### PR DESCRIPTION
**Pull request by Tomekmularczyk**
Fixed #87 by not calling `buildUrl` without a global window object.

Added test, which required splitting test cases by browser and non-browser environment.

### CODE REVIEW

**Comment by tsukhu** [comment]
When will this be merged .. Waiting for this fix :+1:

**Comment by gagichce** [comment]
Still an issue :'(

**Comment by mccabemj** [comment]
@Tomekmularczyk can you please resolve the conflicts. I can then review

**Comment by Tomekmularczyk** [comment]
@mccabemj I will take a look, maybe just create another PR.

**Comment by Tomekmularczyk** [comment]
@mccabemj The `ComponentsSpec.js` looks really messy I guess that's because of the mixed indentation. What I did is created two separate blocks for browser/node environment tests and the  suite was copied inside.

**Pull request merged**
